### PR TITLE
Adding options for English (en-US and en-GB)

### PR DESCRIPTION
**Pull request by webunraveling**
Great work on the translation here. After looking through this, I am really realizing the amount of work that goes into translation for a web site. Please let me know if anything should change. I think I covered everything with all of the configs. Let me know if anything needs to change.

### CODE REVIEW

**Comment by webunraveling** [comment]
Thanks. I have already discovered on thing. Language settings have already been set to *.en. Since that is missing now, the client/frontend still is set to `en` and shows up wrong. No errors show up but take a look at the screenshots below. Is there some way to fix this in the code or would it have to be done in the DB?
language-setting
language-settings-page

**Comment by MarvinZeising** [comment]
just pushed a fix for both cases. should be deployed to staging soon.
would you be so kind as to verify that these are fixed then, please?

**Comment by webunraveling** [comment]
It still shows like the screenshots posted. I don't know the code well enough yet. But could we check the language list and if it is not set, change it to `en-US`? Maybe there is something similar already happening? Or is there another place where the default is being set?

**Comment by MarvinZeising** [comment]
Sorry, my bad. The fix wasn't deployed due to some linting errors.
I've fixed those, now.
Here is the pipeline for the deployment: https://travis-ci.org/JWDeveloper/JWManagement/builds/543829594

**Comment by webunraveling** [comment]
Good thing for the staging environment. I missed a few things. Let me track them all down and see if I can get them fixed.

**Comment by MarvinZeising** [comment]
It's connected to the production environment, though. So be careful when "testing" stuff :-)

**Comment by webunraveling** [comment]
I definitely will be. Right now, I am working inside a virtual machine before pushing anything. :-)

Maybe you'll know where this is. I've tracked down one of the bugs I have created but I cannot find one last bug. When I am logged in and click "Create Project" the language is not automatically filled with the default language. Instead it says "project.entity.languageValues.en"

**Pull request merged**
